### ISSUE TITLE
Update for latest tera-data

### ISSUE THREAD

**Issue by meishuu** [baldera-mods/fast-fire#2]
Due to two commits in tera-data, ([`026014b`](https://github.com/meishuu/tera-data/commit/026014bd1c14b1bae37d711b1b135e6a86e70bf6) and [`5e70034`](https://github.com/meishuu/tera-data/commit/5e70034d0c9d2e3945f39e43a0047d55cec7b0eb)), this module needs to be updated for new/modified `sActionStage` fields.

**Comment by wuaw** [comment]
https://github.com/baldera-mods/fast-fire/pull/3
